CONTIKI_PROJECT = client
all: $(CONTIKI_PROJECT)

# ALL_OS_FILES = $(shell find ../../os/dev -type f -name "*.c")

# CONTIKI_SOURCES_EXCLUDES += $(notdir $(ALL_OS_FILES))

# CONTIKI_SOURCES_EXCLUDES := $(filter-out  timer.c etimer.c process.c log.h autostart.c stimer.c process-mutex.c node-id.c mutex.c critical.c energest.c ctimer.c compower.c atomic.c, $(CONTIKI_SOURCES_EXCLUDES))
# $(info    VAR is $(CONTIKI_SOURCES_EXCLUDES))

# MODULES_SOURCES_EXCLUDES += uip6.c tcpip.c sicslowpan.c 

CONTIKI = ../../
include $(CONTIKI)/Makefile.include